# Generated by Django 5.0.2 on 2024-10-04 14:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="color",
            field=colorfield.fields.ColorField(
                default="#808080",
                image_field=None,
                max_length=7,
                samples=None,
                verbose_name="Цвет в формате HEX",
            ),
        ),
    ]
