# Generated by Django 5.0.2 on 2024-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="age",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Возраст кота",
            ),
        ),
    ]
