# Generated by Django 5.0.2 on 2024-10-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0002_alter_cat_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="age",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Возраст указывается в годах. Например, 1.75 = 1 год и 9 месяцев, 0.42 примерно 5 месяцев.",
                max_digits=4,
                null=True,
                verbose_name="Возраст кота",
            ),
        ),
    ]
