# Generated by Django 5.0.2 on 2024-10-05 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0002_alter_cat_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="age",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Возраст указывается в годах. Например, 1.75 = 1 год и 9 месяцев, 0.42 примерно 5 месяцев.",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.1,
                        message="Минимальный возраст кота должен быть не меньше 0.1 ",
                    ),
                    django.core.validators.MaxValueValidator(
                        35,
                        message="Возраст питомца, к сожалению, не может быть больше 50.",
                    ),
                ],
                verbose_name="Возраст кота",
            ),
        ),
    ]
